[package]
name = "subtitle-fast-ocr"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = ["engine-vision"]
engine-vision = []

[dependencies]
subtitle-fast-types = { path = "../subtitle-fast-types" }
thiserror = "2"

[build-dependencies]
cc = "1"
